### ISSUE TITLE
angular-dropdown-component"' has no default export.

### ISSUE THREAD

**Issue by baj9032** [karanhudia/angular-dropdown-component#3]
I got below error 

ERROR in src/app/app.module.ts(7,8): error TS1192: Module '"D:/Ankit.J.Bhanderi/RND/Angular2/18_07_2018/DOMManipulation/node_modules/angular-dropdown-component/angular-dropdown-component"' has no default export.

![image](https://user-images.githubusercontent.com/16740406/45012826-80c64480-b036-11e8-9487-819d593ec38a.png)

**Comment by karanhudia** [comment]
Hey,

You have to import it like this-

import { DropdownModule } from 'angular-dropdown-component';

Thanks,
Karan

**Comment by karanhudia** [comment]
I have updated the documentation, and also closing the issue.
